name: 'Setup Docker'
description: 'Setup Docker for cross-platform compilation'
inputs:
  username:
    required: false
    default: justinwritescode
    description: the username to use when logging in to the container registry
  github-password:
    required: true
    description: the token to use when logging in to the GitHub container registry (GHCR)
  acr-password:
    required: true
    description: the Azure Container Registry (ACR) login token
  dockerfile:
    required: true
    description: The Dockerfile to build
  tag:
    required: true
    description: The tag to use for the image

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - uses: ./.github/actions/setup-docker
      with:
        password: ${{ inputs.github-password }}

    - uses: docker/login-action@v3
      with: 
        username: thebackroomlife
        password: ${{ inputs.acr-password }}
        registry: thebackroomlife.azurecr.io

    - name: Calculate "MASTODON_VERSION_METADATA"
      shell: bash
      run: |
        MASTODON_VERSION_METADATA="${{ github.sha }}"
        MASTODON_VERSION_METADATA="${STRING:0:8}"
        echo "MASTODON_VERSION_METADATA=$MASTODON_VERSION_METADATA" >> $GITHUB_ENV

    - name: Build & push the Docker image
      uses: docker/build-push-action@v6.7.0
      with:
        tags: |
          ghcr.io/justinwritescode/mastodon:${{ inputs.tag }}
          ghcr.io/justinwritescode/mastodon/${{ inputs.tag }}:${{ github.sha }}
          ghcr.io/justinwritescode/mastodon/${{ inputs.tag }}:latest
          thebackroomlife.azurecr.io/justinwritescode/${{ inputs.tag }}
          thebackroomlife.azurecr.io/justinwritescode/mastodon/${{ inputs.tag }}:${{ github.sha }}
          thebackroomlife.azurecr.io/justinwritescode/mastodon/${{ inputs.tag }}:latest
          thebackroomlife.azurecr.io/mastodon:${{ inputs.tag }}
          thebackroomlife.azurecr.io/mastodon/${{ inputs.tag }}:${{ github.sha }}
          thebackroomlife.azurecr.io/mastodon/${{ inputs.tag }}:latest
          thebackroomlife.azurecr.io/${{ inputs.tag }}:latest
        pull: true
        push: true
        file: ${{ inputs.dockerfile }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max 
        args: MASTODON_VERSION_METADATA="${{ env.MASTODON_VERSION_METADATA }}"