name: 'Setup Docker'
description: 'Setup Docker for cross-platform compilation'
inputs:
  username:
    required: false
    default: justinwritescode
    description: the username to use when logging in to the container registry
  github-password:
    required: true
    description: the token to use when logging in to the GitHub container registry (GHCR)
  acr-password:
    required: true
    description: the Azure Container Registry (ACR) login token
  dockerfile:
    required: true
    description: The Dockerfile to build
  tag:
    required: true
    description: The tag to use for the image
  git-token:
    required: false
    default: ${{ github.token }}
    description: The GitHub token to use for authenticating with the repo

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - uses: ./.github/actions/setup-docker
      with:
        password: ${{ inputs.github-password }}

    - uses: docker/login-action@v3
      with: 
        username: thebackroomlife
        password: ${{ inputs.acr-password }}
        registry: thebackroomlife.azurecr.io

    - name: Calculate "MASTODON_VERSION_METADATA"
      shell: pwsh
      run: |
        $env:MASTODON_VERSION_METADATA="${{ github.sha }}".Substring(0, 8)
        Write-Output "MASTODON_VERSION_METADATA=${env:MASTODON_VERSION_METADATA}" >> $GITHUB_ENV

    - uses: thefringeninja/action-minver@2.0.0-preview1
      id: minver
      with:
        # Optional. Specifies which part of the version to auto-increment.
        auto-increment: patch
        # Optional. Sets custom build metadata for your semantic version.
        # build-metadata: ${{ github.sha }}
        # Optional. Specifies the default pre-release phase.
        default-pre-release-phase: preview
        # Optional. Specifies the minimum version to use when no tags exist.
        minimum-major-minor: 0.0
        # Optional. Specifies the prefix of the tags
        tag-prefix: v
        # Optional. Specifies the log level.
        verbosity: trace

    - name: Build & push the Docker image
      uses: docker/build-push-action@v6.7.0
      with:
        context: .
        pull: true
        push: true
        tags: |
          ghcr.io/justinwritescode/mastodon:${{ inputs.tag }}
          ghcr.io/justinwritescode/mastodon/${{ inputs.tag }}:${{ github.sha }}
          ghcr.io/justinwritescode/mastodon/${{ inputs.tag }}:latest
          thebackroomlife.azurecr.io/${{ inputs.tag }}:latest
          thebackroomlife.azurecr.io/justinwritescode/${{ inputs.tag }}:${{ github.sha }}
          thebackroomlife.azurecr.io/justinwritescode/${{ inputs.tag }}:latest
          thebackroomlife.azurecr.io/justinwritescode/mastodon/${{ inputs.tag }}:${{ github.sha }}
          thebackroomlife.azurecr.io/justinwritescode/mastodon/${{ inputs.tag }}:latest
          thebackroomlife.azurecr.io/mastodon:${{ inputs.tag }}
          thebackroomlife.azurecr.io/mastodon/${{ inputs.tag }}:${{ github.sha }}
          thebackroomlife.azurecr.io/mastodon/${{ inputs.tag }}:latest
        labels: |
          org.opencontainers.image.licenses=AGPL-3.0,MIT
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.source=${{ github.server_url }}/${{ github.action_repository }}
        file: ${{ inputs.dockerfile }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=local,src=./cache
        cache-to: type=gha,dest=./cache
        build-args: MASTODON_VERSION_METADATA="${{ env.MASTODON_VERSION_METADATA }}"

      