# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "git-submodule" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
  assignees:
    - hivchaser
    - justinwritescode
  commit-message:
    prefix: '[git-submodule]: '
    include: "scope"
updates:
  - package-ecosystem: "bundler" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
  assignees:
    - hivchaser
    - justinwritescode
  commit-message:
    prefix: '[rubygems]: '
    include: "scope"
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
  assignees:
    - hivchaser
    - justinwritescode
  commit-message:
    prefix: '[npm]: '
    include: "scope"
