services:
  mastodon:
    image: ghcr.io/justinwritescode/mastodon:all
    entrypoint: ["bash", "/opt/mastodon/bin/entrypoint", "all"]
    env_file:
      - .env.production
    ports:
      - 80:80
    volumes:
      - ./app:/opt/mastodon/app
      - ./app:/app/www/app
      - ./app:/mastodon/app
      - ./config:/config
      - ./config:/opt/mastodon/config
      - ./config:/app/www/config
      - ./config:/mastodon/config
      - ./public:/opt/mastodon/public
      - ./public:/app/www/public
      - ./public:/mastodon/public
      - ./public/system:/opt/mastodon/public/system
      - ./root/etc/letsencrypt/live/thebackroom.life:/etc/letsencrypt/live/thebackroom.life