---
services:
  assets_precompiler:
    image: ghcr.io/poz-world/poz.world:latest
    container_name: assets_precompiler
    volumes:
      - ./public:/opt/mastodon/public
    command: cp /root/.bashrc /root/.profile
    entrypoint:
      ["/opt/mastodon/bin/bundle", "exec", "rake", "assets:precompile"]
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: 4d9118f0b0c03485e5cea6e709bafcb91e90458d4453440c91e03d79a2a09a8986a2c49f7152169aa13f5d45aa48dcb4845444f37866ef0001425cf797f20d1b
      OTP_SECRET: db76eaa56a4e70187b2feee809b0c366ca87cecd6b848f45fab759d07b1cb02f85f5234b528a50c2b158fbdbda35790c0987fafbaf97e6303e8574bf007f7a9f
      ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY: fm3cp0fR8XZ2Ya8GnVuuPMWh9z2Tgszc
      ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT: pmVSAFB75H8FhfbUg3Bs6e7KH9e4i0jS
      ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY: Rxh3Fdwt8moRlEAqGW3co9X20qnDo866
