# This file contains default values, and does not need to be edited. All
# important settings can be changed from the admin interface.

defaults: &defaults
  site_title: <%= ENV.fetch('SITE_TITLE', 'Mastodon') %>
  site_short_description: <%= ENV.fetch('SITE_SHORT_DESCRIPTION', '') %>
  site_description: <%= ENV.fetch('SITE_DESCRIPTION', '') %>
  site_extended_description: <%= ENV.fetch('SITE_EXTENDED_DESCRIPTION', '') %>
  site_terms: ''
  site_contact_username: ''
  site_contact_email: ''
  registrations_mode: 'none'
  profile_directory: true
  closed_registrations_message: ''
  timeline_preview: true
  show_staff_badge: true
  preview_sensitive_media: true
  noindex: false
  theme: <%= ENV.fetch('SITE_THEME', 'system') %>
  trends: true
  trends_as_landing_page: true
  trendable_by_default: false
  reserved_usernames:
    - admin
    - support
    - help
    - root
    - webmaster
    - administrator
    - mod
    - moderator
  disallowed_hashtags: <%= ENV.fetch('DISALLOWED_HASHTAGS', 'Mastodon') %>
  bootstrap_timeline_accounts: ''
  activity_api_enabled: true
  peers_api_enabled: true
  show_domain_blocks: 'disabled'
  show_domain_blocks_rationale: 'disabled'
  require_invite_text: false
  backups_retention_period: 7
  captcha_enabled: <%= ENV.fetch('USE_CAPTCHA', 'true') %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
