s3:
  enabled: <%= ENV['S3_ENABLED'] || 'false' %>
  region: <%= ENV['S3_REGION'] || 'us-east-1' %>
  protocol: <%= ENV['S3_PROTOCOL'] || 'https' %>
  hostname: <%= ENV['S3_HOSTNAME'] || "s3-#{(ENV['S3_REGION'] || 'us-east-1')}.amazonaws.com" %>
  keyPrefix: <%= ENV['S3_KEY_PREFIX'] || nil %>
  multipartThreshold: <%= ENV['S3_MULTIPART_THRESHOLD'] || 15000000 %>
  bucket: <%= ENV['S3_BUCKET'] || nil %>
  signatureVersion: <%= ENV['S3_SIGNATURE_VERSION'] || 'v4' %>
  accessKeyId: <%= ENV['AWS_ACCESS_KEY_ID'] || nil %>
  secretAccessKey: <%= ENV['AWS_ACCESS_KEY_ID'] || nil %>
  permission: <%= ENV['S3_PERMISSION'] || nil %>
  openTimeout: <%= ENV['S3_OPEN_TIMEOUT'] || '5' %>
  readTimeout: <%= ENV['S3_READ_TIMEOUT'] || '5' %>
  retryLimit: <%= ENV['S3_RETRY_LIMIT'] || '0' %>
  endpoint: <%= ENV['S3_ENDPOINT'] || nil %>
  overridePathStyle: <%= ENV['S3_OVERRIDE_PATH_STYLE'] || 'false' %>
  storageClass: <%= ENV['S3_STORAGE_CLASS'] || nil %>
  aliasHost: <%= ENV['S3_ALIAS_HOST'] || nil %>
  cloudfrontHost: <%= ENV['S3_CLOUDFRONT_HOST'] || nil %>
