default: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
elephant: styles/elephant.scss
elephant-contrast: styles/elephant-contrast.scss
elephant-light: styles/elephant-light.scss
purple-haze: styles/purple-haze.scss
colorful-dark: styles/colorful-dark.scss
colorful-light: styles/colorful-light.scss
canta-dark: styles/canta-dark.scss
feelin-blue: styles/feelin-blue.scss
tangerineui: styles/tangerineui.scss
tangerineui-purple: styles/tangerineui-purple.scss
tangerineui-cherry: styles/tangerineui-cherry.scss
tangerineui-lagoon: styles/tangerineui-lagoon.scss
