name: "Setup Docker"
description: "Setup Docker for cross-platform compilation"
inputs:
  username:
    required: false
    default: ${{ github.repository_owner }}
    description: the username to use when logging in to the container registry
  azurecr-username:
    required: false
    default: thebackroomlife
    description: the username to use when logging in to the Azure container registry
  password:
    required: true
    description: the token to use when logging in to the container registry
  registry:
    required: false
    default: ghcr.io
    description: the container registry to log into
  azurecr-registry:
    required: false
    default: thebackroomlife
    description: the Azure container registry to log into
  azurecr-password:
    required: true
    description: the token to use when logging in to the Azure container registry
  docker-build-cloud-username:
    required: false
    description: The username to use when logging in to the Docker Cloud
  docker-build-cloud-password:
    required: false
    description: The password to use when logging in to the Docker Cloud
  docker-build-cloud-endpoint:
    required: false
    description: The endpoint to use when using Docker build cloud

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      if: ${{ inputs.registry && inputs.password && inputs.username }}
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Login to Azure Container Registry
      uses: docker/login-action@v3
      if: ${{ inputs.acr-password && inputs.azurecr-registry && inputs.azurecr-username }}
      with:
        registry: ${{ inputs.azurecr-registry }}.azurecr.io
        username: ${{ inputs.azurecr-username }}
        password: ${{ inputs.azurecr-password }}

    - name: Login to Docker Cloud
      uses: docker/login-action@v3
      if: ${{ inputs.docker-build-cloud-endpoint && inputs.docker-build-cloud-username && inputs.docker-build-cloud-password }}
      with:
        username: ${{ inputs.docker-build-cloud-username }}
        password: ${{ inputs.docker-build-cloud-password }}

    - name: Set up Docker Buildx
      id: buildx-cloud
      uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/amd64,linux/arm64
        driver: cloud
        version: "lab:latest"
        endpoint: ${{ inputs.docker-build-cloud-endpoint }}
        install: true
      if: ${{ inputs.docker-build-cloud-endpoint }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/amd64,linux/arm64
      if: ${{ !inputs.docker-build-cloud-endpoint }}
