name: 'Setup Docker'
description: 'Setup Docker for cross-platform compilation'
inputs:
  username:
    required: false
    default: justinwritescode
    description: the username to use when logging in to the container registry
  token:
    required: false
    default: ${{ secrets.PACKAGES_PAT }}
    description: the token to use when logging in to the container registry
  registry:
    required: false
    default: ghcr.io
    description: the container registry to log into

runs:
  using: 'composite'
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/amd64,linux/arm64

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.token }}