name: Build and Deploy POZ.World

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Convert repository name to lowercase
      id: repo-name
      run: echo "::set-output name=lowercase_repo::$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')"

    - name: Build and Push Docker Image
      uses: ./.github/actions/build-and-push-docker-image
      with:
        git-token: ${{ secrets.HIVCHASER_PACKAGES_PAT }}
        github-password: ${{ secrets.HIVCHASER_PACKAGES_PAT }}
        username: ${{ github.repository_owner }}
        acr-password: ${{ secrets.AZURECR_KEY }}
        tag: |
          ghcr.io/${{ steps.repo-name.outputs.lowercase_repo }}
          thebackroomlife.azurecr.io/poz.world
        tag-prefix: pwv
        description: Your self-hosted social media platform for the HIV community
        dockerfile: Dockerfile.poz.world
