name: Docker Image CI

on:
  push:
    branches: [ "thebackroombranding" ]
  pull_request:
    branches: [ "thebackroombranding" ]

permissions: write-all

jobs:

  build-xplat-base:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Docker for multi-platform builds
      run: |
        docker buildx create --name mybuilder --use
        docker buildx inspect --bootstrap
        sudo mkdir -p /etc/docker
        echo '{"features": {"buildkit": true}}' | sudo tee /etc/docker/daemon.json
        sudo systemctl restart docker
        docker run --privileged --rm tonistiigi/binfmt --install all
    - name: Build the Docker image
      run: |
        docker login -u=justinwritescode -p="${{ secrets.PACKAGES_PAT }}" ghcr.io
        docker buildx build --file Dockerfile "." --tag ghcr.io/justinwritescode/mastodon:xplat --platform="linux/arm64,linux/amd64" --push
        
  build-thebackroom-life:
    needs: build-xplat-base
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker login -u=justinwritescode -p="${{ secrets.PACKAGES_PAT }}" ghcr.io
        docker build --file Dockerfile.thebackroom.life "." --tag ghcr.io/justinwritescode/mastodon:thebackroom.life
        docker image push ghcr.io/justinwritescode/mastodon:thebackroom.life
        
