name: Docker Image CI

on:
  push:
    branches: [ "thebackroombranding" ]
  pull_request:
    branches: [ "thebackroombranding" ]

permissions: write-all

jobs:

  build-xplat-base:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/amd64,linux/arm64

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: justinwritescode
        password: ${{ secrets.PACKAGES_PAT }}

    - name: Build & push the Docker image
      uses: docker/build-push-action@v6.7.0
      with:
        name: ${{ steps.buildx.outputs.name }}
        labels: ghcr.io/justinwritescode/mastodon:xplat
        pull: true
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        
  build-thebackroom-life:
    needs: build-xplat-base
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/amd64,linux/arm64

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: justinwritescode
        password: ${{ secrets.PACKAGES_PAT }}

    - name: Build & push the Docker image
      uses: docker/build-push-action@v6.7.0
      with:
        name: ${{ steps.buildx.outputs.name }}
        labels: ghcr.io/justinwritescode/mastodon:thebackroom.life
        pull: true
        file: Dockerfile.thebackroom.life
        platforms: linux/amd64,linux/arm64
        