name: Docker Image CI

on:
  push:
    branches: [ "thebackroombranding" ]
  pull_request:
    branches: [ "thebackroombranding" ]

permissions: write-all

jobs:

  build-xplat-base:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker login -u=justinwritescode -p="${{ secrets.PACKAGES_PAT }}" ghcr.io
        docker build --file Dockerfile "." --tag ghcr.io/justinwritescode/mastodon:xplat
        docker image push ghcr.io/justinwritescode/mastodon:xplat
        
  build-thebackroom-life:
    needs: build-xplat-base
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker login -u=justinwritescode -p="${{ secrets.PACKAGES_PAT }}" ghcr.io
        docker build --file Dockerfile.thebackroom.life "." --tag ghcr.io/justinwritescode/mastodon:thebackroom.life
        docker image push ghcr.io/justinwritescode/mastodon:thebackroom.life
        
