# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build & Deploy - pozworld

concurrency: 
  group: ${{ github.workflow}}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  workflow_dispatch:

env: 
  REDIS_URL: ${{ secrets.REDIS_URL }}
  DB_NAME: ${{ vars.DB_NAME }}
  DB_SSLMODE: ${{ vars.DB_SSLMODE }}
  DB_USER: ${{ vars.DB_USER }}
  DB_HOST: ${{ vars.DB_HOST }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_PASS: ${{ secrets.DB_PASSWORD }}
  DATABASE_URL: "${{ vars.DB_USER }}:${{ secrets.DB_PASSWORD }}@${{ vars.DB_HOST }}:5432"
  CI: "true"

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - uses: ./.github/actions/build-and-push-docker-image
      with:
        git-token: ${{ secrets.HIVCHASER_PACKAGES_PAT }}
        github-password: ${{ secrets.HIVCHASER_PACKAGES_PAT }}
        username: ${{ github.repository_owner }}
        acr-password: ${{ secrets.AZURECR_KEY }}
        tag: |
          ghcr.io/${{ github.repository }}
          thebackroomlife.azurecr.io/poz.world
        tag-prefix: pwv
        description: Your self-hosted social media platform for the HIV community
        dockerfile: Dockerfile.poz.world

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'pozworld'
        slot-name: 'production'
        publish-profile: ${{ secrets.POZ_WORLD_PUBLISH_PROFILE }}
        images: 'ghcr.io/${{ github.repository }}:${{ github.sha }}'
