name: Docker Image CI

on:
  push:
    branches: [ "thebackroombranding" ]
  pull_request:
    branches: [ "thebackroombranding" ]

concurrency:
  group: thebackroomlife-ci-docker
  cancel-in-progress: true

permissions: write-all

jobs:
        
  build-thebackroom-life:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/setup-docker
      with:
        git-token: ${{ secrets.PACKAGES_PAT }}
        github-password: ${{ secrets.PACKAGES_PAT }}
        username: hivchaser
        username: hivchaser

    - uses: docker/login-action@v3
      with: 
        username: thebackroomlife
        password: ${{ secrets.AZURECR_KEY }}
        registry: thebackroomlife.azurecr.io

    - name: Build & push the Docker image
      uses: docker/build-push-action@v6.7.0
      with:
        tags: |
          ghcr.io/justinwritescode/mastodon:thebackroom.life
          ghcr.io/justinwritescode/mastodon/thebackroom.life:${{ github.sha }}
          ghcr.io/justinwritescode/mastodon/thebackroom.life:latest
          thebackroomlife.azurecr.io/justinwritescode/mastodon:thebackroom.life
          thebackroomlife.azurecr.io/justinwritescode/mastodon/thebackroom.life:${{ github.sha }}
          thebackroomlife.azurecr.io/justinwritescode/mastodon/thebackroom.life:latest
          thebackroomlife.azurecr.io/mastodon:thebackroom.life
          thebackroomlife.azurecr.io/mastodon/thebackroom.life:${{ github.sha }}
          thebackroomlife.azurecr.io/mastodon/thebackroom.life:latest
          thebackroomlife.azurecr.io/thebackroom.life:latest
        pull: true
        push: true
        file: Dockerfile.thebackroom.life
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max 
        
  build-thebackroom-streaming:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - uses: ./.github/actions/setup-docker
      with:
        password: ${{ secrets.PACKAGES_PAT }}

    - uses: docker/login-action@v3
      with: 
        username: thebackroomlife
        password: ${{ secrets.AZURECR_KEY }}
        registry: thebackroomlife.azurecr.io

    - name: Build & push the Docker image
      uses: docker/build-push-action@v6.7.0
      with:
        tags: |
          ghcr.io/justinwritescode/mastodon:streaming
          ghcr.io/justinwritescode/mastodon/streaming:${{ github.sha }}
          ghcr.io/justinwritescode/mastodon/streaming:latest
          thebackroomlife.azurecr.io/justinwritescode/mastodon:streaming
          thebackroomlife.azurecr.io/justinwritescode/mastodon/streaming:${{ github.sha }}
          thebackroomlife.azurecr.io/justinwritescode/mastodon/streaming:latest
          thebackroomlife.azurecr.io/mastodon:streaming
          thebackroomlife.azurecr.io/mastodon/streaming:${{ github.sha }}
          thebackroomlife.azurecr.io/mastodon/streaming:latest
        pull: true
        push: true
        file: Dockerfile.thebackroom.life
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
