name: Build Base Docker Image

on:
  workflow_dispatch:
      

concurrency:
  group: thebackroomlife-ci-docker
  cancel-in-progress: true

permissions: write-all

jobs:

  build-xplat-base:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - uses: ./.github/actions/build-and-push-docker-image
      id: build-mastodon
      name: 'Build TheBackroom.life'
      with:
        github-password: ${{ github.token }} 
        acr-password: ${{ secrets.AZURECR_KEY }}
        dockerfile: ./Dockerfile
        tag: xplat
