name: Docker Image CI

on:
  push:
    branches: [ "thebackroombranding" ]
  pull_request:
    branches: [ "thebackroombranding" ]

concurrency:
  group: thebackroomlife-ci-docker
  cancel-in-progress: true

permissions: write-all

jobs:

  build-xplat-base:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download the build cache
      uses: actions/cache@v3
      with: 
        key: xplat-build-cache
        path: ./build-cache
    
    - uses: ./.github/actions/setup-docker
      with:
        password: ${{ secrets.PACKAGES_PAT }}

    - uses: docker/login-action@v3
      with: 
        username: thebackroomlife
        password: ${{ secrets.AZURECR_KEY }}
        registry: thebackroomlife.azurecr.io

    - name: Build & push the Docker image
      uses: docker/build-push-action@v6.7.0
      with:
        tags: |
          mastodon:xplat
          justinwritescode/mastodon:xplat
          ghcr.io/justinwritescode/mastodon:xplat
          thebackroomlife.azurecr.io/mastodon:xplat
          thebackroomlife.azurecr.io/justinwritescode/mastodon:xplat
        pull: true
        push: true
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        cache-from: ./build-cache
        cache-to: ./build-cache
        
  build-thebackroom-life:
    needs: build-xplat-base
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download the build cache
      uses: actions/cache@v3
      with: 
        key: xplat-build-cache
        path: ./build-cache

    - uses: ./.github/actions/setup-docker
      with:
        password: ${{ secrets.PACKAGES_PAT }}

    - uses: docker/login-action@v3
      with: 
        username: thebackroomlife
        password: ${{ secrets.AZURECR_KEY }}
        registry: thebackroomlife.azurecr.io

    - name: Build & push the Docker image
      uses: docker/build-push-action@v6.7.0
      with:
        tags: |
          mastodon:thebackroom.life
          justinwritescode/mastodon:thebackroom.life
          ghcr.io/justinwritescode/mastodon:thebackroom.life
          thebackroomlife.azurecr.io/mastodon:thebackroom.life
          thebackroomlife.azurecr.io/justinwritescode/mastodon:thebackroom.life
        pull: true
        push: true
        file: Dockerfile.thebackroom.life
        platforms: linux/amd64,linux/arm64
        cache-from: ./build-cache
        cache-to: ./build-cache        
        
  build-thebackroom-streaming:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download the build cache
      uses: actions/cache@v3
      with: 
        key: xplat-build-cache
        path: ./build-cache
    
    - uses: ./.github/actions/setup-docker
      with:
        password: ${{ secrets.PACKAGES_PAT }}

    - uses: docker/login-action@v3
      with: 
        username: thebackroomlife
        password: ${{ secrets.AZURECR_KEY }}
        registry: thebackroomlife.azurecr.io

    - name: Build & push the Docker image
      uses: docker/build-push-action@v6.7.0
      with:
        tags: |
          mastodon:streaming
          justinwritescode/mastodon:streaming
          ghcr.io/justinwritescode/mastodon:streaming
          thebackroomlife.azurecr.io/mastodon:streaming
          thebackroomlife.azurecr.io/justinwritescode/mastodon:streaming
        pull: true
        push: true
        file: Dockerfile.thebackroom.life
        platforms: linux/amd64,linux/arm64
        cache-from: ./build-cache
        cache-to: ./build-cache
        