name: Docker Image CI

on:
  push:
    branches: [ "thebackroombranding" ]
  pull_request:
    branches: [ "thebackroombranding" ]

concurrency:
  group: thebackroomlife-ci-docker
  cancel-in-progress: true

permissions: write-all

jobs:

  build-xplat-base:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download the build cache
      uses: actions/cache@v3
      with: 
        key: xplat-build-cache
        path: ./build-cache
    
    - uses: ./.github/actions/setup-docker
      with:
        password: ${{ secrets.PACKAGES_PAT }}

    - name: Build & push the Docker image
      uses: docker/build-push-action@v6.7.0
      with:
        name: ${{ steps.buildx.outputs.name }}
        labels: ghcr.io/justinwritescode/mastodon:xplat
        pull: true
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        cache-from: ./build-cache
        cache-to: ./build-cache
        
  build-thebackroom-life:
    needs: build-xplat-base
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download the build cache
      uses: actions/cache@v3
      with: 
        key: xplat-build-cache
        path: ./build-cache

    - uses: ./.github/actions/setup-docker
      with:
        password: ${{ secrets.PACKAGES_PAT }}

    - name: Build & push the Docker image
      uses: docker/build-push-action@v6.7.0
      with:
        name: ${{ steps.buildx.outputs.name }}
        labels: ghcr.io/justinwritescode/mastodon:thebackroom.life
        pull: true
        file: Dockerfile.thebackroom.life
        platforms: linux/amd64,linux/arm64
        cache-from: ./build-cache
        cache-to: ./build-cache        
        
  build-thebackroom-streaming:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download the build cache
      uses: actions/cache@v3
      with: 
        key: xplat-build-cache
        path: ./build-cache
    
    - uses: ./.github/actions/setup-docker
      with:
        password: ${{ secrets.PACKAGES_PAT }}

    - name: Build & push the Docker image
      uses: docker/build-push-action@v6.7.0
      with:
        # name: ${{ steps.buildx.outputs.name }}
        labels: ghcr.io/justinwritescode/mastodon:thebackroom.life
        pull: true
        file: Dockerfile.thebackroom.life
        platforms: linux/amd64,linux/arm64
        cache-from: ./build-cache
        cache-to: ./build-cache
        