# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - pozworld

concurrency: 
  group: POZ.world CD
  cancel-in-progress: true

on:
  push:
    branches:
      - poz.world
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_24c66707976845cfb7cb6360bf574946 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d318538d136349d7a980433f665962b8 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_24c66707976845cfb7cb6360bf574946 }}/poz.world:${{ github.sha }}
        file: ./Dockerfile.poz.world

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'pozworld'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4cfc4e7521f1492186964fb06d8f6f5f }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_24c66707976845cfb7cb6360bf574946 }}/poz.world:${{ github.sha }}'
