# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build & Deploy - pozworld

on:
  push:
    branches:
      - poz.world
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - uses: ./.github/actions/setup-docker
      with:
        password: ${{ secrets.PACKAGES_PAT }}

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_083c1d1dcf2148c39073af25da373b36 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_738c8b140eac4ff7bc8695b3d55df1cb }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_083c1d1dcf2148c39073af25da373b36 }}/justinwritescode/poz.world:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'pozworld'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1f44889051db4923964789b0ba3eda66 }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_083c1d1dcf2148c39073af25da373b36 }}/justinwritescode/poz.world:${{ github.sha }}'
