# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - thebackroomlife

on:
  push:
    branches:
      - thebackroombranding
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_67e0016c3cbd4daa8dbea73dc3b99808 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4bec953bfd1f45f7b17daffc272a22e5 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_67e0016c3cbd4daa8dbea73dc3b99808 }}/justinwritescode/mastodon:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'thebackroomlife'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0f6e008cec6e4cf595ee12656ee0592d }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_67e0016c3cbd4daa8dbea73dc3b99808 }}/justinwritescode/mastodon:${{ github.sha }}'